<?php
require_once __DIR__ . '/../config/config.php';
require_once __DIR__ . '/../config/database.php';
require_once __DIR__ . '/../includes/functions.php';
require_once __DIR__ . '/../includes/auth.php';
auth_check();
$user = current_user();
if (!in_array($user['role_name'], ['Staff Gudang','Viewer'], true)) redirect(APP_URL . '/pages/dashboard.php');
$db = getDB(); $uid = (int)$user['id'];
$total_items = (int)$db->query("SELECT COUNT(*) FROM items WHERE is_active=1")->fetch_row()[0];
$stock = $db->query("SELECT i.code,i.name,u.abbreviation,COALESCE(SUM(s.quantity),0) qty FROM items i JOIN units u ON u.id=i.unit_id LEFT JOIN stock s ON s.item_id=i.id WHERE i.is_active=1 GROUP BY i.id ORDER BY i.name LIMIT 100")->fetch_all(MYSQLI_ASSOC);
$tx = [];
foreach ([['Barang Masuk','stock_in'],['Barang Keluar','stock_out'],['Transfer','transfers']] as [$label,$table]) {
 $st=$db->prepare("SELECT reference_no,transaction_date,created_at FROM `$table` WHERE user_id=? ORDER BY created_at DESC LIMIT 20"); $st->bind_param('i',$uid); $st->execute();
 foreach($st->get_result()->fetch_all(MYSQLI_ASSOC) as $r){$r['type']=$label;$tx[]=$r;} $st->close();
}
usort($tx,fn($a,$b)=>strcmp($b['created_at'],$a['created_at'])); $tx=array_slice($tx,0,20);
?><!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Portal Gudang</title><meta name="theme-color" content="#0d6efd"><link rel="manifest" href="<?=APP_URL?>/manifest.json"><script>(function(){try{var t=localStorage.getItem('mw_theme')||'light';document.documentElement.setAttribute('data-bs-theme',t)}catch(e){}})();</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.2/font/bootstrap-icons.min.css"><style>body{padding-bottom:76px}.view{display:none}.view.active{display:block}.bottom{position:fixed;bottom:0;left:0;right:0;background:var(--bs-body-bg);border-top:1px solid var(--bs-border-color);display:flex;z-index:10}.bottom button{flex:1;border:0;background:none;padding:.6rem .2rem;color:var(--bs-secondary-color);font-size:.75rem}.bottom button.active{color:var(--bs-primary)}.bottom i{display:block;font-size:1.3rem}.card{border-color:var(--bs-border-color)}</style></head><body><header class="sticky-top bg-primary text-white p-3 d-flex justify-content-between"><strong><i class="bi bi-boxes"></i> Portal Gudang</strong><button class="btn btn-sm btn-outline-light" id="theme"><i class="bi bi-moon-stars"></i></button></header><main class="container py-3">
<section class="view active" id="home"><h5>Halo, <?=htmlspecialchars($user['name'])?></h5><div class="row g-2 my-3"><div class="col-6"><div class="card p-3"><small>Item Aktif</small><b class="fs-3"><?=$total_items?></b></div></div><div class="col-6"><div class="card p-3"><small>Aktivitas Saya</small><b class="fs-3"><?=count($tx)?></b></div></div></div><h6>Aktivitas Terbaru</h6><?php foreach(array_slice($tx,0,5) as $r):?><div class="card p-2 mb-2"><b><?=htmlspecialchars($r['reference_no'])?></b><small><?=$r['type']?> · <?=date('d/m/Y',strtotime($r['transaction_date']))?></small></div><?php endforeach;?></section>
<section class="view" id="stock"><input class="form-control mb-3" id="q" placeholder="Cari kode/nama barang"><div id="items"><?php foreach($stock as $r):?><div class="card p-3 mb-2 item" data-q="<?=htmlspecialchars(strtolower($r['code'].' '.$r['name']))?>"><div class="d-flex justify-content-between"><span><b><?=htmlspecialchars($r['name'])?></b><small class="d-block text-body-secondary"><?=htmlspecialchars($r['code'])?></small></span><strong><?=number_format($r['qty'])?> <?=htmlspecialchars($r['abbreviation'])?></strong></div></div><?php endforeach;?></div></section>
<section class="view" id="trx"><h5>Transaksi Saya</h5><?php foreach($tx as $r):?><div class="card p-3 mb-2"><b><?=htmlspecialchars($r['reference_no'])?></b><span><?=$r['type']?></span><small class="text-body-secondary"><?=date('d/m/Y',strtotime($r['transaction_date']))?></small></div><?php endforeach;?></section>
<section class="view" id="profile"><div class="card p-4 text-center"><i class="bi bi-person-circle fs-1"></i><h5><?=htmlspecialchars($user['name'])?></h5><p><?=htmlspecialchars($user['email'])?><br><span class="badge text-bg-primary"><?=htmlspecialchars($user['role_name'])?></span></p><a class="btn btn-danger" href="<?=APP_URL?>/auth/logout.php">Keluar</a></div></section></main>
<nav class="bottom"><?php foreach([['home','house','Beranda'],['stock','boxes','Stok'],['trx','clock-history','Transaksi'],['profile','person','Profil']] as $i=>$n):?><button data-view="<?=$n[0]?>" class="<?=$i===0?'active':''?>"><i class="bi bi-<?=$n[1]?>"></i><?=$n[2]?></button><?php endforeach;?></nav><script>document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.view,.bottom button').forEach(x=>x.classList.remove('active'));document.getElementById(b.dataset.view).classList.add('active');b.classList.add('active')});q.oninput=()=>document.querySelectorAll('.item').forEach(x=>x.hidden=!x.dataset.q.includes(q.value.toLowerCase()));theme.onclick=()=>{let t=document.documentElement.getAttribute('data-bs-theme')==='dark'?'light':'dark';document.documentElement.setAttribute('data-bs-theme',t);localStorage.setItem('mw_theme',t)};if('serviceWorker'in navigator)navigator.serviceWorker.register('<?=APP_URL?>/sw.js');</script></body></html>